# Generated by Django 4.2.17 on 2025-01-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_pin_code', models.CharField(max_length=4)),
                ('expired_date', models.DateField(auto_now_add=True)),
                ('money', models.FloatField(default=0)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.user')),
            ],
        ),
    ]
